services:
  mysql:
    image: 'mysql:8.0-oracle'
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=database
    ports:
      - "3306:3306"
